### ISSUE TITLE
[epic] Analyse and Plan Data Warehouse and UI changes

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/pm#69]
This issue is about systematically analysing and planning our Data Warehouse and UI changes as they relate to supporting:

* New metrics in both Data Warehouse and UI
* Summing metrics across risks (for overall ranking by country)
* Multiple time granularities
* Surfacing time and temporal granularities in the UI

Sub issues:

* [x] Data warehouse structure - DONE - resulting plan of changes at https://github.com/cybergreen-net/aggregator/issues/25
  * [ ] IP deduplication within different time granularities #75 
* [x] API changes - TODO
* [x] Changes re metrics - DONE part of API and DW change
* [x] Design reference data system - #74 

## Sample user stories

**These are just sample. Up to date set in Slide Deck. Do not comment on these here.** 

As a Viewer I want to see rank of a country based on total DDoS risk so that I can see what is source of biggest risk

As a Viewer I want to easily understand what metrics I am looking, their source and context so that I understand clearly what I am looking at

As a Viewer I want to see a time series graph of country (total or per risk), ASN (ditto) or risk performance at the most relevant (or different) granularity so that I get the best perspective 

As a Viewer I want to compare countries performance at monthly or annual basis not just week so that I get a better overall picture

## Analysis and Plan

See this in progress [Slide Deck](https://docs.google.com/presentation/d/14-tJ3Ca0qstmgwLENQh5jflChB4MxZoUkA96fFoqGbU/edit#slide=id.g344642f18_18)

**Comment by rgrp** [comment]
I estimate this will take 40h+ of work alone.

**Comment by rufuspollock** [comment]
Actions for tomorrow:

* [x] Slide 11 showing RDS as of beta-2
* [x] Write slide(s) explaining postgres cubes functionality (and cubes in general)
* [x] Add Slide 15 and do example sql expressions (including cube)
  * Different time granularities
  * Show how we would recompute tables we now have (so we can refactor nicely)
* [x] Add slide 16 with example code queries for these from nodejs 

Review http://databrewery.org/

**Comment by rufuspollock** [comment]
Data warehouse planning largely done.

Next steps:

* [x] Create a DW task epic with lots of subitems in aggregator repo
* [x] Plan query and API changes
  * e.g. do we want to just have /api/cube?... as well as the basic dimension options (?) - internally these other options e.g. `/api/country` are a combination of dimension + cube data
* [ ] Finalize UX changes and start creating issues
* [x] Design reference data management (slide 22)

**Comment by rufuspollock** [comment]
**Time in the UI**

Talked about this extensively yesterday with @aaronkaplan and @zelima

Overall sense: we need to think about main user journey and user stories. Generally, we want to make good defaults and may confine a lot of the optionality such as different time granularities or time points to an "explorer" app.

**Comment by rufuspollock** [comment]
FIXED. Marking as fixed. There will no doubt be a bit more to do esp re the API and UX changes but a good chunk done.
