### ISSUE TITLE
[epic] Reference data updates

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/pm#76]
* [x] Split out reference datasets to own repos:
  * [x] `refdata-risk`
  * [x] `refdata-country`
    * [x] move data
  * [x] `refdata-asn`
    * [x] move data
* [x] Refactor each of those repos to new structure - as per new docs
* [x] Add amplification factor to risk reference data
* [ ] NOT CRITICAL *Merge https://github.com/cybergreen-net/asname-historical with `refdata-asn` repo*

**Comment by zelima** [comment]
New repos set up for reference data
- risk - https://github.com/cybergreen-net/refdata-risk
- country - https://github.com/cybergreen-net/refdata-country
- asn - https://github.com/cybergreen-net/refdata-asn

Notes:
- Only repo for risk contains actual data
- datapackage.json's are constructed according to "new" columns, that csv files should have. (may need to modify)

**Comment by rgrp** [comment]
FIXED. Modulo a few tidy ups suggested in comments in https://github.com/cybergreen-net/pm/commit/788da41644321cc490e67783dcf3cb17ac61940c

**Comment by rufuspollock** [comment]
@zelima i assume we have not moved data because not on critical path. How long would this take?

**Comment by zelima** [comment]
@rgrp Easy with country, as soon as I start RDS work tomorrow. Not sure about ASN (complete version, with names) as there is no csv version of mapping `as-number -> asn-name -> country`  yet

**Comment by zelima** [comment]
@rufuspollock reference data is moved to repos. But yet we are missing scripts for getting them

**Comment by rufuspollock** [comment]
FIXED. This was a fixed a while ago.
