### ISSUE TITLE
[Epic] March 2017 Report Deliverables for JPCERT

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/pm#90]
- [ ] Stats portal v.2 with API Access and ASN, country level statistics - lots of screenshots etc 
  - [x] Any improvements/changes/ additional functions made between December until now to API functionality, ASN/country level stats and visuals [Atomatic] https://github.com/cybergreen-net/pm/issues/91
  - [ ] Any changes/improvements to orchestration, ETL, automation since December [Cosive]
- [ ] Platform Operation - Description of overall portal operation (any downtime described). [Aaron, arasto] 
- [x] Test Report [Atomatic, Cosive] #92 
  - Includes the testing on system requirement specification and user experiences and improvements
- [ ] Final Documentation on CyberGreen Statistics Portal version 2 
  - [x]  user manual, metrics description, “How to” guide on use of portal [Atomatic] #93 
- [ ] Portal Security Assessment [Aaron]
- [x] Platform Integration - Deliverable - screenshots of all pages [Atomatic] #94 
- [ ] Report of Conducted Training  [Yurie, Aaron, Arastoo]

**Comment by rufuspollock** [comment]
FIXED. At Atomatic we've completed all our items and so we'll mark as FIXED as we assume everything was done as needed for delivery.

**Comment by aaronkaplan** [comment]
confirmed
