### ISSUE TITLE
Test Report March 2017

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/pm#92]
### summery
Includes the testing on system requirement specification and user experiences and improvements

[Google doc](https://docs.google.com/document/d/1kqVkNxfiZCe2llvSfUmNAK_qFUgeDSCUqlyqVjoRQGQ/edit)

### tasks
- [x] Provide with results of tests in docs for
  - [x] [stats-new](https://travis-ci.org/cybergreen-net/stats-new)  
     - [x] some improvements first https://github.com/cybergreen-net/stats-new/issues/220
  - [x] [aggregator](https://travis-ci.org/cybergreen-net/aggregator)
  - [x] [cg graphs](https://travis-ci.org/cybergreen-net/cg-graphs)
- [x] User experience tests  
  - what does this exactly mean?

**Comment by zelima** [comment]
Results of tests are in [google docs](https://docs.google.com/document/d/1kqVkNxfiZCe2llvSfUmNAK_qFUgeDSCUqlyqVjoRQGQ/edit)

@rufuspollock / @shiweiart Please update with User experience tests (if relevant)

**Comment by rufuspollock** [comment]
@zelima did you look at the previous report and compare it? I think you can do most of this and ping @shiweiart on channel if you need more.

**Comment by zelima** [comment]
FIXED from our side. reopopen if needed

**Comment by ataslim** [comment]
@zelima For section III (user experience tests) can you provide a solution for 

"User story: As a CERT and a policy maker I want to see the trend of the Global DDOS potential so that I have a sense of the global security level in the world."

**Comment by zelima** [comment]
FIXED doc updated. (I had 1 solution for 2 different user stories, as they were related. Now they are separated)
